[tool.isort]
profile="black"
atomic=true
extend_skip_glob="migrations,scripts"
line_length=88

[tool.black]
extend-exclude="migrations,scripts"

# pyproject.toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
